apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: njl4z2hn1-python
  janus-idp.io/tekton: njl4z2hn1-python
  backstage.io/kubernetes-id: njl4z2hn1-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: njl4z2hn1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
